export const categories = ["celo", "ethereum", "web3", "blog"];

export const projects = [
  {
    title: "Voting Dao",
    description: "This is a DAO where it costs 0.0001 ether to be a member. Members of the DAO can submit proposals and vote on proposals by others. \r\nThis is a test app on the rinkeby test network",
    imageurl: "https://ipfs.io/ipfs/QmeFUAYULjruTAuYm9NehcdFGEKSX6KNYnj3ooAP8XtUbB",
    liveurl: "https://daoist.netlify.app/",
    github: "https://github.com/narteysarso/votingdao",
    tags: ["hardhat", "ethers", "solidity", "react", "antdesign"],
    category: "ethereum",
  },
  {
    title: "Crypto Price and news",
    description: "This is provides price information for top performing cryptocurrencies as well as current crypto news. It also enables you to transfer Ethers from your MetaMask wallet to any ethereum account on the blockchain",
    imageurl: "https://ipfs.io/ipfs/QmUedBDhmWe7FbdEqKep85jnPVbkjof1haxZMwUnMp449y",
    liveurl: "https://dappersite.netlify.app/",
    github: "https://github.com/narteysarso/DApper",
    tags: ["axios", "chartjs", "ethers", "react", "antdesign"],
    category: "web3",
  },
  {
    title: "AgroFund",
    description: "This is a celo blockchain powered platform that provides crowdfund services for agribusiness and cultivations.",
    imageurl: "https://ipfs.io/ipfs/Qmaqnn2H5M5VveFcdJ9r5CmdwYxXNL2goAbCT8uybrebrd",
    liveurl: "https://agrofund.vercel.app/",
    github: "https://github.com/narteysarso/agrofund",
    tags: ["hardhat", "web3js", "solidity", "react", "antdesign"],
    category: "celo",
  },
  {
    title: "Genrez",
    description: "This is a celo blockchain based music sharing website that allows creator/artist to share music with their funs.",
    imageurl: "https://ipfs.io/ipfs/QmSjt6tgSdYxVH6T9EkhUjbAbCP3TWHLEPJ69ZnWA3umy5",
    liveurl: "https://genrez-celo.vercel.app/",
    github: "https://github.com/narteysarso/genrez-celo",
    tags: ["hardhat", "web3js", "solidity", "react", "bootstrap", "theGraph"],
    category: "celo",
  },
  {
    title: "IDX Token",
    description: "IDX EXCHANGE is a Dapp that allows you to buy IDX tokens with Ether. You can also transfer IDX tokens to others.",
    imageurl: "https://ipfs.io/ipfs/QmQpB7MAjkG7DjakYwrN1jUx1KvDhRvu8PaTeaGDkwE3Fa",
    liveurl: "https://idxtoken.netlify.app/home",
    github: "https://github.com/narteysarso/idx-exchange",
    tags: ["hardhat", "ethers", "solidity", "react", "antdesign"],
    category: "ethereum",
  },
  {
    title: "Banking Dapp",
    description: "An etheruem DApp that allows users to deposit Eth in and withdraw Eth from a smart contract",
    imageurl: "https://ipfs.io/ipfs/QmYZ6p8zSZ2AL8pzzdhJJ6XXKX4g99HrKC1g2CFyGPCo7V",
    liveurl: "https://bank-dapp-pink.vercel.app",
    github: "https://github.com/narteysarso/bank-dapp",
    tags: ["hardhat", "ethers", "solidity", "react", "antdesign"],
    category: "ethereum",
  },
  {
    title: "Real-Time Smart Contract",
    description: "Events in The Frontend | 7 min read - Published on 25 Jun, 2022",
    imageurl: "https://ipfs.io/ipfs/QmNqCPaAwUxhKzne4Aj8L4GAvwgZyeJ2awesy1b6ZerdYL",
    liveurl: "https://narteysarso.hashnode.dev/real-time-smart-contract-events-in-the-frontend",
    
    tags: ["hardhat", "ethers", "solidity", "react",],
    category: "blog",
  },
];
