export const categories = ["celo", "ethereum", "web3", "blog", "audit"];

export const projects = [
  {
    title: "Crypto Price and news",
    description: "This is provides price information for top performing cryptocurrencies as well as current crypto news. It also enables you to transfer Ethers from your MetaMask wallet to any ethereum account on the blockchain",
    imageurl: "https://ipfs.io/ipfs/QmUedBDhmWe7FbdEqKep85jnPVbkjof1haxZMwUnMp449y",
    liveurl: "https://dappersite.netlify.app/",
    github: "https://github.com/narteysarso/DApper",
    tags: ["axios", "chartjs", "ethers", "react", "antdesign"],
    category: "web3",
  },
  {
    title: "AgroFund",
    description: "This is a celo blockchain powered platform that provides crowdfund services for agribusiness and cultivations.",
    imageurl: "https://ipfs.io/ipfs/Qmaqnn2H5M5VveFcdJ9r5CmdwYxXNL2goAbCT8uybrebrd",
    liveurl: "https://agrofund.vercel.app/",
    github: "https://github.com/narteysarso/agrofund",
    tags: ["hardhat", "web3js", "solidity", "react", "antdesign"],
    category: "celo",
  },
  {
    title: "Genrez",
    description: "This is a celo blockchain based music sharing website that allows creator/artist to share music with their funs.",
    imageurl: "https://ipfs.io/ipfs/QmSjt6tgSdYxVH6T9EkhUjbAbCP3TWHLEPJ69ZnWA3umy5",
    liveurl: "https://genrez-celo.vercel.app/",
    github: "https://github.com/narteysarso/genrez-celo",
    tags: ["hardhat", "web3js", "solidity", "react", "bootstrap", "theGraph"],
    category: "celo",
  },
  {
    title: "Executable Agreement Protocol",
    description: "Contributor: An smart contract protocol that turns legal contracts to executable smart contracts",
    imageurl: "https://ipfs.io/ipfs/QmdWTUkpSEQr7fc7jb8LeRkEHiX8fHyH35nc9kk9rsNeK8",
    liveurl: "http://executable-agreement-protocol-frontend-ekxg.vercel.app/",
    github: "https://github.com/narteysarso/executable-agreement-protocol",
    tags: ["hardhat", "ethers", "solidity", "react", "ant.design"],
    category: "ethereum",
  },
  {
    title: "Split Protocol",
    description: "Contributor: An etheruem DApp that allows users share and pay bills with different tokens",
    imageurl: "https://proud-moon-1292.on.fleek.co/_next/static/media/favicon.a48d04e7.ico",
    liveurl: "https://ethglobal.com/showcase/split-protocol-h6r1a",
    github: "https://github.com/yanghakim/Split-Protocol",
    tags: ["hardhat", "ethers", "solidity"],
    category: "ethereum",
  },
  {
    title: "IDX Token",
    description: "IDX EXCHANGE is a Dapp that allows you to buy IDX tokens with Ether. You can also transfer IDX tokens to others.",
    imageurl: "https://ipfs.io/ipfs/QmQpB7MAjkG7DjakYwrN1jUx1KvDhRvu8PaTeaGDkwE3Fa",
    liveurl: "https://idxtoken.netlify.app/home",
    github: "https://github.com/narteysarso/idx-exchange",
    tags: ["hardhat", "ethers", "solidity", "react", "ant.design"],
    category: "ethereum",
  },
  {
    title: "Voting Dao",
    description: "This is a DAO where it costs 0.0001 ether to be a member. Members of the DAO can submit proposals and vote on proposals by others. \r\nThis is a test app on the rinkeby test network",
    imageurl: "https://ipfs.io/ipfs/QmeFUAYULjruTAuYm9NehcdFGEKSX6KNYnj3ooAP8XtUbB",
    liveurl: "https://daoist.netlify.app/",
    github: "https://github.com/narteysarso/votingdao",
    tags: ["hardhat", "ethers", "solidity", "react", "antdesign"],
    category: "ethereum",
  },
  {
    title: "Banking Dapp",
    description: "An etheruem DApp that allows users to deposit Eth in and withdraw Eth from a smart contract",
    imageurl: "https://ipfs.io/ipfs/QmYZ6p8zSZ2AL8pzzdhJJ6XXKX4g99HrKC1g2CFyGPCo7V",
    liveurl: "https://bank-dapp-pink.vercel.app",
    github: "https://github.com/narteysarso/bank-dapp",
    tags: ["hardhat", "ethers", "solidity", "react", "ant.design"],
    category: "ethereum",
  },
  {
    title: "Real-Time Smart Contract",
    description: "Events in The Frontend | 7 min read - Published on 25 Jun, 2022",
    imageurl: "https://ipfs.io/ipfs/QmNqCPaAwUxhKzne4Aj8L4GAvwgZyeJ2awesy1b6ZerdYL",
    liveurl: "https://narteysarso.hashnode.dev/real-time-smart-contract-events-in-the-frontend",
    github: "https://github.com/narteysarso/using-smart-contract-in-frontend",
    tags: ["hardhat", "ethers", "solidity", "react",],
    category: "blog",
  },
  {
    title: "Generating Ethereum Addresses",
    description: "How Ethereum Addresses are Generated with JavaScript and Ethers| 6 min read - Published on 30 Aug, 2022",
    imageurl: "https://ipfs.io/ipfs/QmXJZDLv5LNbSdRSakav85wCmfbeeBTwgEFjRU5fhWwBVM",
    liveurl: "https://narteysarso.hashnode.dev/how-ethereum-addresses-are-generated",
    github: "https://replit.com/@narteysarso/Generating-Ethereum-Address#index.js",
    tags: ["javascript", "ethers"],
    category: "blog",
  },
  {
    title: "Encoding and Verifing Ethereum Address: EIP-55",
    description: "Ethereum Address Encoding and Verification: EIP-55 implementation in Javascript| 3 min read - Published on 18 Aug, 2022",
    imageurl: "https://ipfs.io/ipfs/QmaAe62GxPEhxafxRbzsSHKvZoxvoDHvTPBqWj1C6QgRmr",
    liveurl: "https://narteysarso.hashnode.dev/how-ethereum-addresses-are-generated",
    tags: ["javascript", "ethers"],
    category: "blog",
  },
  {
    title: "DOS Attack",
    description: "This project demonstrates a smart contract DOS attack and prevention.",
    imageurl: "https://ipfs.io/ipfs/QmaLvm5A4Z1rcW7UqdvSYDKvHj3584e9x4MR5JAKC2uTj3",
    github: "https://github.com/narteysarso/dos-attack",
    tags: ["hardhat", "ethers", "solidity",],
    category: "audit",
  },
  {
    title: ".delegatecall Attack",
    description: "This project demonstrats a .delegatecall attack and prevention.",
    imageurl: "https://ipfs.io/ipfs/QmZizMVXbik6hBfrMXxrB3JbPLV42hrskGoyJ5LxjzZWMX",
    github: "https://github.com/narteysarso/delegate-call-attack",
    tags: ["hardhat", "ethers", "solidity",],
    category: "audit",
  },
  {
    title: "Randomness Attack",
    description: "This project demonstrates randomness attack and it fixes in solidity.",
    imageurl: "https://ipfs.io/ipfs/QmNnPbciVoCbaHEhV7dTmRjNmioZbNjycYXxRcw2BwpXHe",
    github: "https://github.com/narteysarso/randomness-attack",
    tags: ["hardhat", "ethers", "solidity",],
    category: "audit",
  },
  {
    title: "Reentrancy Attack",
    description: "This repo consist of various contracts to test and prevent reentrancy attack.",
    imageurl: "https://ipfs.io/ipfs/QmZizMVXbik6hBfrMXxrB3JbPLV42hrskGoyJ5LxjzZWMX",
    github: "https://github.com/narteysarso/reentrancy-attack-solidity",
    tags: ["hardhat", "ethers", "solidity",],
    category: "audit",
  },
  {
    title: "tx.origin Attack",
    description: "This project demonstrates a basic tx.origin attack and prevention",
    imageurl: "https://ipfs.io/ipfs/QmZizMVXbik6hBfrMXxrB3JbPLV42hrskGoyJ5LxjzZWMX",
    github: "https://github.com/narteysarso/tx.origin-attack",
    tags: ["hardhat", "ethers", "solidity",],
    category: "audit",
  },
  {
    title: "Malicious Contract Attack",
    description: "This project demonstrates a malicious attack and prevention",
    imageurl: "https://ipfs.io/ipfs/QmNnPbciVoCbaHEhV7dTmRjNmioZbNjycYXxRcw2BwpXHe",
    github: "https://github.com/narteysarso/malicious-attack",
    tags: ["hardhat", "ethers", "solidity",],
    category: "audit",
  },
];
